//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacilityBookingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facility
    {
        public Facility()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public string ID { get; set; }
        public System.DateTime BookDate { get; set; }
        public string Location { get; set; }
        public string TS09 { get; set; }
        public string TS10 { get; set; }
        public string TS11 { get; set; }
        public string TS12 { get; set; }
        public string TS13 { get; set; }
        public string TS14 { get; set; }
        public string TS15 { get; set; }
        public string TS16 { get; set; }
        public string TS17 { get; set; }
        public string TS18 { get; set; }
        public string TS19 { get; set; }
        public string TS20 { get; set; }

        public string this[int i]
        {
            get
            {
                switch (i)
                {
                    case 0: return this.TS09;
                    case 1: return this.TS10;
                    case 2: return this.TS11;
                    case 3: return this.TS12;
                    case 4: return this.TS13;
                    case 5: return this.TS14;
                    case 6: return this.TS15;
                    case 7: return this.TS16;
                    case 8: return this.TS17;
                    case 9: return this.TS18;
                    case 10: return this.TS19;
                    case 11: return this.TS20;
                    default: return null;
                }
            }
            set
            {
                switch (i)
                {
                    case 0: this.TS09 = value; break;
                    case 1: this.TS10 = value; break;
                    case 2: this.TS11 = value; break;
                    case 3: this.TS12 = value; break;
                    case 4: this.TS13 = value; break;
                    case 5: this.TS14 = value; break;
                    case 6: this.TS15 = value; break;
                    case 7: this.TS16 = value; break;
                    case 8: this.TS17 = value; break;
                    case 9: this.TS18 = value; break;
                    case 10: this.TS19 = value; break;
                    case 11: this.TS20 = value; break;
                }
            }
        }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
